apiVersion: v1
kind: Service
metadata:
  name:   {{ .Values.backend.nameOverride }}
spec:
  type:  ClusterIP
  selector:
    app: {{ .Values.backend.nameOverride }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}


---


apiVersion: v1
kind: Service
metadata:
  name:   {{ .Values.front.nameOverride }}
spec:
  type:  ClusterIP
  selector:
    app: {{ .Values.front.nameOverride }}
  ports:
    - port: {{ .Values.front.service.port }}
      targetPort: {{ .Values.front.service.targetPort }}

